service: orderbook-events-service 

provider:
  name: aws
  runtime: python3.6
  profile: loidsig
  region: us-east-1
  stage: prod
  memorySize: 128

package:
  include:
    - binance_orderbook_events.py
    - cobinhood_orderbook_events.py
    - orderbook_features.py
  exclude:
    - requirements.txt
    - serverless.yml
    - package.json
    - package-lock.json
    - node_modules/**

functions:
  cobinhood-events:
    role: arn:aws:iam::309597787617:role/lambda_basic_execution
    handler: cobinhood_orderbook_events.main
    events:
      - schedule:
          name: cobinhood-orderbook-scheduler
          description: 'cobinhood raw events schedule'
          rate: rate(1 minute)
          enabled: true
    onError: arn:aws:sns:us-east-1:309597787617:orderbook_pipeline_notifications
    timeout: 60
  binance-events:
    role: arn:aws:iam::309597787617:role/lambda_basic_execution
    handler: binance_orderbook_events.main
    events:
      - schedule:
          name: binance-orderbook-scheduler
          description: 'binance raw events schedule'
          rate: rate(1 minute)
          enabled: true
    onError: arn:aws:sns:us-east-1:309597787617:orderbook_pipeline_notifications
    timeout: 60
  orderbook-features:
    role: arn:aws:iam::309597787617:role/lambda_basic_execution
    handler: orderbook_features.main
    reservedConcurrency: 400
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:309597787617:raw_orderbook_events
          batchSize: 1
    onError: arn:aws:sns:us-east-1:309597787617:orderbook_pipeline_notifications
    timeout: 60

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
